-- Run as SYSDBA

CREATE TABLESPACE PF_TEST DATAFILE 'PF_TEST_TS.ORA' SIZE 10M AUTOEXTEND ON NEXT 10M;
CREATE TEMPORARY TABLESPACE PF_TEST_TEMP TEMPFILE 'PF_TEST_TS_TEMP.ORA' SIZE 5M AUTOEXTEND ON NEXT 5M;


DEFINE SCHEMA_NAME = PF_TEST_SCHEMA;
DEFINE TS = PF_TEST;
DEFINE TEMP_TS = PF_TEST_TEMP;

DROP USER &SCHEMA_NAME CASCADE;

CREATE USER &SCHEMA_NAME
  IDENTIFIED BY gsKhFB
  DEFAULT TABLESPACE &TS
  TEMPORARY TABLESPACE &TEMP_TS
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  
grant CONNECT         to &SCHEMA_NAME;
grant RESOURCE        to &SCHEMA_NAME;
alter user &SCHEMA_NAME default role all;

grant CREATE MATERIALIZED VIEW to &SCHEMA_NAME;
grant CREATE PROCEDURE         to &SCHEMA_NAME;
grant CREATE SYNONYM           to &SCHEMA_NAME;
grant CREATE TYPE              to &SCHEMA_NAME;
grant CREATE VIEW              to &SCHEMA_NAME;
GRANT CREATE SEQUENCE 		   TO &SCHEMA_NAME;
GRANT SELECT ANY DICTIONARY    TO &SCHEMA_NAME;

revoke UNLIMITED TABLESPACE    from &SCHEMA_NAME;
alter user &SCHEMA_NAME quota unlimited on &TS;
  